In [12]:
from google.colab import drive 
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [11]:
import tensorflow
import tensorflow
import os, shutil

In [13]:
base_dir = '/content/gdrive/MyDrive/내_클라우드플랫폼'

train_dir = '/content/gdrive/MyDrive/내_클라우드플랫폼/train'
validation_dir = '/content/gdrive/MyDrive/내_클라우드플랫폼/validation'
test_dir = '/content/gdrive/MyDrive/내_클라우드플랫폼/test'

train_brush = '/content/gdrive/MyDrive/내_클라우드플랫폼/train/brush'
train_flag = '/content/gdrive/MyDrive/내_클라우드플랫폼/train/flag'
train_mattress = '/content/gdrive/MyDrive/내_클라우드플랫폼/train/mattress'
train_pad = '/content/gdrive/MyDrive/내_클라우드플랫폼/train/pad'
train_umbrella = '/content/gdrive/MyDrive/내_클라우드플랫폼/train/umbrella'

validation_brush = '/content/gdrive/MyDrive/내_클라우드플랫폼/validation/brush'
validation_flag = '/content/gdrive/MyDrive/내_클라우드플랫폼/validation/flag'
validation_mattress = '/content/gdrive/MyDrive/내_클라우드플랫폼/validation/mattress'
validation_pad = '/content/gdrive/MyDrive/내_클라우드플랫폼/validation/pad'
validation_umbrella = '/content/gdrive/MyDrive/내_클라우드플랫폼/validation/umbrella'

test_brush = '/content/gdrive/MyDrive/내_클라우드플랫폼/test/brush'
test_flag = '/content/gdrive/MyDrive/내_클라우드플랫폼/test/flag'
test_mattress = '/content/gdrive/MyDrive/내_클라우드플랫폼/test/mattress'
test_pad = '/content/gdrive/MyDrive/내_클라우드플랫폼/test/pad'
test_umbrella = '/content/gdrive/MyDrive/내_클라우드플랫폼/test/umbrella'

In [14]:
print('train brush len :', len(os.listdir(train_brush)))

train brush len : 17


In [17]:
from tensorflow.keras import layers
from tensorflow.keras import models

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

model.add(layers.Flatten())
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(5, activation='softmax'))

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 148, 148, 32)      896       
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 74, 74, 32)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 72, 72, 64)        18496     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 36, 36, 64)        0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 34, 34, 128)       73856     
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 17, 17, 128)       0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 15, 15, 128)      

In [19]:
from tensorflow.keras import optimizers

model.compile(loss='categorical_crossentropy',
              optimizer=optimizers.RMSprop(lr=1e-4),
              metrics=['acc'])

In [20]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        train_dir,
        target_size=(150, 150),
        batch_size=20,
        class_mode='categorical')

validation_generator = test_datagen.flow_from_directory(
        validation_dir,
        target_size=(150, 150),
        batch_size=50,
        class_mode='categorical')

Found 76 images belonging to 5 classes.
Found 20 images belonging to 5 classes.


In [21]:
for data_batch, labels_batch in train_generator:
    print('배치 데이터 크기:', data_batch.shape)
    print('배치 레이블 크기:', labels_batch.shape)
    break

배치 데이터 크기: (20, 150, 150, 3)
배치 레이블 크기: (20, 5)


In [22]:
history = model.fit_generator(
      train_generator,
      #steps_per_epoch=10,
      epochs=20,
      validation_data=validation_generator,
      #validation_steps=50
      )

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1844: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/20
4/4 [==============================] - 26s 6s/step - loss: 1.6292 - acc: 0.1598 - val_loss: 1.5947 - val_acc: 0.2000
Epoch 2/20
4/4 [==============================] - 4s 1s/step - loss: 1.5667 - acc: 0.3007 - val_loss: 1.6088 - val_acc: 0.2000
Epoch 3/20
4/4 [==============================] - 4s 1s/step - loss: 1.5101 - acc: 0.3176 - val_loss: 1.5258 - val_acc: 0.3500
Epoch 4/20
4/4 [==============================] - 4s 1s/step - loss: 1.4485 - acc: 0.5345 - val_loss: 1.5955 - val_acc: 0.2000
Epoch 5/20
4/4 [==============================] - 4s 1s/step - loss: 1.4366 - acc: 0.3751 - val_loss: 1.4132 - val_acc: 0.4000
Epoch 6/20
4/4 [==============================] - 4s 1s/step - loss: 1.2966 - acc: 0.5673 - val_loss: 1.3485 - val_acc: 0.4500
Epoch 7/20
4/4 [==============================] - 4s 1s/step - loss: 1.2486 - acc: 0.5759 - val_loss: 1.2990 - val_acc: 0.5000
Epoch 8/20
4/4 [==============================] - 4s 1s/step - loss: 1.1164 - acc: 0.6438 - val_loss: 1.2242 -

In [23]:
model.save('recycling_small.h5')

In [24]:
from tensorflow.keras.models import load_model

model=load_model('recycling_small.h5')

In [25]:
test_generator = test_datagen.flow_from_directory(
        test_dir,
        target_size=(150, 150),
        batch_size=50,
        class_mode='categorical')

Found 20 images belonging to 5 classes.


In [26]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
1/1 [==============================] - 1s 589ms/step - loss: 1.0238 - acc: 0.4500
acc: 45.00%


In [27]:
import numpy as np

output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:1905: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  warnings.warn('`Model.predict_generator` is deprecated and '


{'brush': 0, 'flag': 1, 'mattress': 2, 'pad': 3, 'umbrella': 4}
[[0.000 0.147 0.000 0.000 0.852]
 [0.208 0.005 0.721 0.007 0.059]
 [0.367 0.307 0.038 0.002 0.285]
 [0.009 0.009 0.029 0.001 0.952]
 [0.068 0.011 0.162 0.103 0.656]
 [0.010 0.017 0.720 0.206 0.046]
 [0.364 0.100 0.238 0.024 0.274]
 [0.003 0.630 0.003 0.000 0.363]
 [0.014 0.003 0.089 0.426 0.468]
 [0.027 0.061 0.610 0.003 0.299]
 [0.070 0.099 0.134 0.034 0.663]
 [0.441 0.128 0.236 0.012 0.183]
 [0.402 0.071 0.067 0.062 0.397]
 [0.047 0.080 0.143 0.247 0.483]
 [0.290 0.010 0.594 0.031 0.076]
 [0.196 0.105 0.078 0.018 0.603]
 [0.059 0.018 0.736 0.044 0.143]
 [0.194 0.114 0.444 0.007 0.241]
 [0.011 0.838 0.002 0.000 0.149]
 [0.003 0.271 0.157 0.009 0.560]]


In [54]:
pred = []
for i in range(len(output)):
    maxval = max(output[i])
    cls = np.where(output[i]==maxval)[0][0]
    out = [k for k,v in test_generator.class_indices.items() if v == cls][0]
    print('%s번째 이미지는 %s 확률로 %s로 분류되었습니다.'%(i, round(maxval*100,2), out))

0번째 이미지는 85.2 확률로 umbrella로 분류되었습니다.
1번째 이미지는 72.13 확률로 mattress로 분류되었습니다.
2번째 이미지는 36.74 확률로 brush로 분류되었습니다.
3번째 이미지는 95.22 확률로 umbrella로 분류되었습니다.
4번째 이미지는 65.61 확률로 umbrella로 분류되었습니다.
5번째 이미지는 72.03 확률로 mattress로 분류되었습니다.
6번째 이미지는 36.41 확률로 brush로 분류되었습니다.
7번째 이미지는 63.0 확률로 flag로 분류되었습니다.
8번째 이미지는 46.82 확률로 umbrella로 분류되었습니다.
9번째 이미지는 61.02 확률로 mattress로 분류되었습니다.
10번째 이미지는 66.34 확률로 umbrella로 분류되었습니다.
11번째 이미지는 44.11 확률로 brush로 분류되었습니다.
12번째 이미지는 40.25 확률로 brush로 분류되었습니다.
13번째 이미지는 48.34 확률로 umbrella로 분류되었습니다.
14번째 이미지는 59.36 확률로 mattress로 분류되었습니다.
15번째 이미지는 60.33 확률로 umbrella로 분류되었습니다.
16번째 이미지는 73.57 확률로 mattress로 분류되었습니다.
17번째 이미지는 44.43 확률로 mattress로 분류되었습니다.
18번째 이미지는 83.8 확률로 flag로 분류되었습니다.
19번째 이미지는 55.97 확률로 umbrella로 분류되었습니다.


In [56]:
test_generator[0]

(array([[[[0.224, 0.208, 0.173],
          [0.216, 0.200, 0.165],
          [0.208, 0.192, 0.157],
          ...,
          [0.482, 0.494, 0.459],
          [0.478, 0.490, 0.455],
          [0.486, 0.498, 0.455]],
 
         [[0.196, 0.180, 0.145],
          [0.216, 0.200, 0.165],
          [0.204, 0.188, 0.153],
          ...,
          [0.463, 0.475, 0.439],
          [0.475, 0.486, 0.451],
          [0.471, 0.482, 0.439]],
 
         [[0.196, 0.169, 0.137],
          [0.200, 0.173, 0.141],
          [0.200, 0.173, 0.141],
          ...,
          [0.475, 0.478, 0.447],
          [0.467, 0.471, 0.439],
          [0.459, 0.471, 0.435]],
 
         ...,
 
         [[0.118, 0.125, 0.114],
          [0.118, 0.125, 0.114],
          [0.106, 0.114, 0.102],
          ...,
          [0.663, 0.686, 0.686],
          [0.592, 0.616, 0.616],
          [0.639, 0.663, 0.663]],
 
         [[0.110, 0.118, 0.106],
          [0.122, 0.129, 0.118],
          [0.129, 0.137, 0.125],
          ...,
      